name: deploy

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Send Restart Signal
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://${{ secrets.BASE_PTERODACTYL_URL }}/api/client/servers/${{ secrets.PTERODACTYL_SERVER_ID }}/power'
          method: 'POST'
          customHeaders:
            Content-Type: application/json
            Authorization: Bearer ${{ secrets.PTERODACTYL_API_KEY }}
          data:
            signal: restart
